apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namespace: dj-controller

images:
  - name: djkubelet/dj-controller
    newTag: latest
    newName: dj-controller

# Apply this patch to use pod template with locally built spotify-ctl
#patchesStrategicMerge:
#- deployment-patch.yaml
