#!/bin/bash
set -euo pipefail

# Development only
#set -x
#ACCESS_TOKEN=$(kubectl get secrets spotify-oauth -ojsonpath='{.data.accesstoken}' | base64 --decode)

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

auth_header() {
    set +u
    token=$ACCESS_TOKEN
    if [ "$token" == "" ]; then
        token=$(cat /etc/spotify-oauth/accesstoken)
    fi
    set -u
    echo "Authorization: Bearer $token"
}

sp_curl() {
    curl -s -H "$(auth_header)" "$@"
}

normalize_str() {
    S=${1// /-}                                 # remove spaces from $1
    S=${S//:/-}                                 # replace : with -
    S=$(echo "$S" | tr "[:upper:]" "[:lower:]") # lowercase
    S=$(echo "$S" | LANG=c tr -cd '[:print:]')  # remove non ascii characters
    S=$(echo "$S" | cut -c-253)                 # trim to max 253 characters
    echo "$S"
}

ms_to_min_sec() {
    ms=$1
    ((full_minutes = ms / 60000))
    # Remaining after full minutes is removed
    ((remaining_ms = ms % 60000))
    ((full_secs = remaining_ms / 1000))
    # Remaining after full minutes and full seconds is removed
    ((remaining_ms2 = remaining_ms % 1000))

    # TODO: Figure out how the spotify apps do rounding.
    if (("$remaining_ms2" > 500)); then
        extra_sec=1
    else
        extra_sec=0
    fi
    ((seconds =full_secs + extra_sec))
    echo "$full_minutes:$(printf "%02d" "$seconds")"
}

get_track() {
    track="${1/spotify:track:/}"
    sp_curl "https://api.spotify.com/v1/tracks/$track"
}

now_playing() {
    sp_curl "https://api.spotify.com/v1/me/player"
}

find_pod() {
    track=$1
    kubectl get pods -ojson |
        jq -r ".items[] | select(.metadata.ownerReferences[].name == \"$track\")"
}

find_pod_name() {
    track=$1
    find_pod "$track" | jq -r ".metadata.name"
}

manage() {
    export TRACK_NAME=$1
    echo 1>&2 "Create pod for new track: $TRACK_NAME"
    local track
    track="$(kubectl get tr "$TRACK_NAME" -ojson)"

    declare -xg TRACK_UID
    TRACK_UID="$(jq -r '.metadata.uid' <<<"$track")"

    declare -x TRACK_URI
    TRACK_URI="$(jq -r '.spec.uri' <<<"$track")"
    normalized_track_uri="$(normalize_str "${TRACK_URI/spotify:track:/}")"

    declare -x POD_NAME
    POD_NAME="${TRACK_NAME}-${normalized_track_uri}-"

    envsubst <"$DIR/pod.tmpl.yaml" |
        kubectl create -f - || true
}

update_track_info() {
    track_name=$1
    echo 1>&2 "Update track info: $track_name"

    track_uri="$(kubectl get tr "$track_name" -ojsonpath='{.spec.uri}')"
    track=$(get_track "$track_uri")

    t_name=$(jq -r '.name' <<<"$track")
    album=$(jq -r '.album.name' <<<"$track")

    # Get duration as minutes:seconds
    duration=$(jq -r '.duration_ms' <<<"$track")
    duration=$(ms_to_min_sec "$duration")

    artist_name=$(jq -r '.artists[0].name' <<<"$track")
    patch="$(
        cat <<EOF
{ "status": {
        "track": {
            "album": "$album",
            "artist": "$artist_name",
            "duration": "$duration",
            "name": "$t_name"
        }
    }
}
EOF
    )"
    kubectl patch track "$track_name" --type merge --patch "$patch"
}

print_n_x() {
    pad="$(printf '%*s' "$1")"
    echo -n "${pad// /$2}"
}

progress_bar() {
    width=$1
    ratio=$2
    print_n_x "$(jq -n "$ratio * $width | floor")" .
    echo -n '|'
    print_n_x "$(jq -n "(1 - $ratio) * $width | ceil")" .
}

update_track_progress() {
    track_name=$1
    echo 1>&2 "Update track progress: $track_name"
    pod=$(find_pod "$track_name")

    # TODO get from status.track.duration
    duration_ms="0"
    progress_ms="0"

    pod_phase=$(jq -r '.status.phase' <<<"$pod")
    if [[ "$pod_phase" == "Succeeded" ]]; then
        phase="Done"
    elif [[ "$pod_phase" == "Running" ]]; then
        phase="Playing"
        np=$(now_playing)

        # TODO Verify is playing and uri
        #is_playing=$(jq -r '.is_playing' <<<"$np")
        #playing_uri=$(jq -r '.item.uri' <<<"$np")

        duration_ms=$(jq -r '.item.duration_ms' <<<"$np")
        progress_ms=$(jq -r '.progress_ms' <<<"$np")

    else
        phase="Unknown - $pod_phase"
    fi
    duration_string=$(ms_to_min_sec "$duration_ms")
    progress_string=$(ms_to_min_sec "$progress_ms")
    ratio=$(jq -n "$progress_ms/$duration_ms")
    pb=$(progress_bar 20 "$ratio")

    patch="$(
        cat <<EOF
{ "status": {
        "phase": "$phase",
        "progress": {
            "bar": "$pb",
            "string": "$progress_string",
            "ratio": "$ratio",
            "ratioString": "$progress_string / $duration_string"
        }
    }
}
EOF
    )"
    kubectl patch track "$track_name" --type merge --patch "$patch"

}

control() {
    for track in $(kubectl get tr -ojsonpath='{.items[*].metadata.name}'); do
        if [[ $(find_pod_name "$track") == "" ]]; then
            manage "$track"
            update_track_info "$track"
        else
            # TODO Skip tracks that are done
            update_track_progress "$track"
        fi
    done
}

while true; do
    sleep 5
    control
done
