#!/bin/bash
set -eo pipefail

if [ "$1" == "-v" ]; then
    set -x
fi
set -u

POD_TEMPLATE="${POD_TEMPLATE:-./template/prod-pod.tmpl.yaml}"

n_kubectl() {
    kubectl --namespace="$NAMESPACE" "$@"
}

auth_header() {
    set +u
    token=$ACCESS_TOKEN
    if [ "$token" == "" ]; then
        token=$(cat /etc/spotify-oauth/accesstoken)
    fi
    set -u
    echo "Authorization: Bearer $token"
}

sp_curl() {
    curl -s -H "$(auth_header)" "$@"
}

normalize_str() {
    S=${1// /-}                                 # remove spaces from $1
    S=${S//:/-}                                 # replace : with -
    S=$(echo "$S" | tr "[:upper:]" "[:lower:]") # lowercase
    S=$(echo "$S" | LANG=c tr -cd '[:print:]')  # remove non ascii characters
    S=$(echo "$S" | cut -c-253)                 # trim to max 253 characters
    echo "$S"
}

ms_to_min_sec() {
    ms=$1
    ((full_minutes = ms / 60000))
    # Remaining after full minutes is removed
    ((remaining_ms = ms % 60000))
    ((full_secs = remaining_ms / 1000))
    # Remaining after full minutes and full seconds is removed
    ((remaining_ms2 = remaining_ms % 1000))

    # TODO: Figure out how the spotify apps do rounding.
    if (("$remaining_ms2" > 500)); then
        extra_sec=1
    else
        extra_sec=0
    fi
    ((seconds = full_secs + extra_sec))
    echo "$full_minutes:$(printf "%02d" "$seconds")"
}

get_track() {
    track="${1/spotify:track:/}"
    sp_curl "https://api.spotify.com/v1/tracks/$track"
}

now_playing() {
    sp_curl "https://api.spotify.com/v1/me/player"
}

find_pod() {
    track=$1
    n_kubectl get pods -ojson |
        jq -r ".items[] | select(.metadata.ownerReferences[].name == \"$track\")"
}

find_pod_name() {
    track=$1
    track_name="$(jq -r '.metadata.name' <<<"$track")"
    find_pod "$track_name" | jq -r ".metadata.name"
}

print_n_x() {
    pad="$(printf '%*s' "$1")"
    echo -n "${pad// /$2}"
}

progress_bar() {
    width=$1
    ratio=$2
    print_n_x "$(jq -n "$ratio * $width | floor")" .
    echo -n '|'
    print_n_x "$(jq -n "(1 - $ratio) * $width | ceil")" .
}

manage() {
    track=$1

    declare -xg TRACK_NAME
    TRACK_NAME="$(jq -r '.metadata.name' <<<"$track")"
    echo 1>&2 "Create pod for new track: $TRACK_NAME"

    declare -xg TRACK_UID
    TRACK_UID="$(jq -r '.metadata.uid' <<<"$track")"

    declare -x TRACK_URI
    TRACK_URI="$(jq -r '.spec.uri' <<<"$track")"
    normalized_track_uri="$(normalize_str "${TRACK_URI/spotify:track:/}")"

    declare -x POD_NAME
    POD_NAME="${TRACK_NAME}-${normalized_track_uri}-"

    envsubst <"$POD_TEMPLATE" |
        n_kubectl create -f -
}

update_track_info() {
    track=$1
    track_name="$(jq -r '.metadata.name' <<<"$track")"
    echo 1>&2 "Update track info: $track_name"

    track_uri="$(jq -r '.spec.uri' <<<"$track")"
    sp_track=$(get_track "$track_uri")

    t_name=$(jq -r '.name' <<<"$sp_track")
    album=$(jq -r '.album.name' <<<"$sp_track")

    # Get duration as minutes:seconds
    duration_ms=$(jq -r '.duration_ms' <<<"$sp_track")
    # TODO check for null from jq
    duration=$(ms_to_min_sec "$duration_ms")

    artist_name=$(jq -r '.artists[0].name' <<<"$sp_track")
    patch="$(
        cat <<EOF
{ "status": {
        "track": {
            "album": "$album",
            "artist": "$artist_name",
            "duration": "$duration",
            "duration_ms": "$duration_ms",
            "name": "$t_name"
        }
    }
}
EOF
    )"
    n_kubectl patch track "$track_name" --type merge --patch "$patch"
}

update_track_progress() {
    track=$1

    track_name="$(jq -r '.metadata.name' <<<"$track")"
    #echo 1>&2 "Update track progress: $track_name"

    pod=$(find_pod "$track_name")

    duration_ms="$(jq -r '.status.track.duration_ms' <<<"$track")"
    progress_ms="0"

    pod_phase=$(jq -r '.status.phase' <<<"$pod")
    if [[ "$pod_phase" == "Succeeded" ]]; then
        phase="Done"
        progress_ms="$duration_ms"
    elif [[ "$pod_phase" == "Pending" ]]; then
        phase="Queued"
    elif [[ "$pod_phase" == "Failed" ]]; then
        phase="Failed"
        # TODO: Handle failure, recreate pod or something.
    elif [[ "$pod_phase" == "Running" ]]; then
        phase="Playing"
        np=$(now_playing)

        # TODO Verify is playing and uri
        #is_playing=$(jq -r '.is_playing' <<<"$np")
        #playing_uri=$(jq -r '.item.uri' <<<"$np")

        duration_ms=$(jq -r '.item.duration_ms' <<<"$np")
        progress_ms=$(jq -r '.progress_ms' <<<"$np")

    else
        phase="Unknown - $pod_phase"
    fi
    if [[ "$duration_ms" == "null" ]]; then
        duration_ms=0
    fi
    if [[ "$progress_ms" == "null" ]]; then
        progress_ms=0
    fi
    duration_string=$(ms_to_min_sec "$duration_ms")
    progress_string=$(ms_to_min_sec "$progress_ms")
    ratio=$(jq -n "$progress_ms/$duration_ms")
    if [ "$ratio" == "null" ]; then
        ratio="0"
    fi
    pb=$(progress_bar 20 "$ratio")

    patch="$(
        cat <<EOF
{ "status": {
        "phase": "$phase",
        "progress": {
            "bar": "$pb",
            "string": "$progress_string",
            "ratio": "$ratio",
            "ratioString": "$progress_string / $duration_string"
        }
    }
}
EOF
    )"
    #echo 1>&2 "$patch"
    #echo 1>&2 "$(jq -r '{"status": {"phase":.status.phase, "progress":.status.progress}}' <<<"$track")"
    diff="$(jq -r "$patch == {\"status\": {\"phase\":.status.phase, \"progress\":.status.progress}}" <<<"$track")"
    if [[ "$diff" != "true" ]]; then
        n_kubectl patch track "$track_name" --type merge --patch "$patch"
    fi
}

control() {
    n_kubectl get tr -ojson |
        jq --compact-output -r '.items[]' |
        while read -r track; do
            phase="$(jq -r '.status.phase' <<<"$track")"
            if [[ "$phase" == "Done" ]]; then
                # Don't do anything with tracks that are Done
                :
            elif [[ $(find_pod_name "$track") == "" ]]; then
                # A new track. Let the controller manage it.
                manage "$track"
                update_track_info "$track"
            else
                update_track_progress "$track"
            fi
        done
}

while true; do
    sleep 5
    time control
    echo "control loop ran"
done
