apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tracks.dj-kubelet.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: dj-kubelet.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tracks
    # singular name to be used as an alias on the CLI and for display
    singular: track
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Track
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tr

  additionalPrinterColumns:
    - name: Track Name
      type: string
      JSONPath: .status.track.name
      priority: 0
    - name: Artist
      type: string
      JSONPath: .status.track.artist
      priority: 0
    - name: Status
      type: string
      JSONPath: .status.phase
      priority: 0
    - name: Duration
      type: string
      JSONPath: .status.track.duration
      priority: 1
    - name: Progress
      type: string
      JSONPath: .status.progress.ratioString
      priority: 1
    - name: Progress Bar
      type: string
      JSONPath: .status.progress.bar
      priority: 1
